### ISSUE TITLE
Activation of doclinks fails the build

### ISSUE THREAD

**Issue by PeterWippermann** [jenkinsci/doclinks-plugin#6]
I activated the "Publish document" feature in my build to archive the three reports the [Maven Versions Plugin](http://www.mojohaus.org/versions-maven-plugin/plugin-info.html) generated for me.
However, that leads to an error and thus fails the build:

```
ERROR: Processing failed due to a bug in the code. Please report this to jenkinsci-users@googlegroups.com
java.lang.IllegalStateException: cannot change build result while in COMPLETED
	at hudson.model.Run.setResult(Run.java:459)
	at hudson.plugins.doclinks.m2.DocLinksMavenReporter.end(DocLinksMavenReporter.java:97)
	at hudson.maven.AbstractMavenBuilder.end(AbstractMavenBuilder.java:104)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:859)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
project=hudson.maven.MavenModuleSet@7d57ab8b[G2P-Archetype-Test]
project.getModules()=[hudson.maven.MavenModule@69464677[G2P-Archetype-Test/com.ing.diba.g2p:platform-archetype][G2P-Archetype-Test/com.ing.diba.g2p:platform-archetype][relativePath:]]
project.getRootModule()=hudson.maven.MavenModule@69464677[G2P-Archetype-Test/com.ing.diba.g2p:platform-archetype][G2P-Archetype-Test/com.ing.diba.g2p:platform-archetype][relativePath:]
FATAL: cannot change build result while in COMPLETED
java.lang.IllegalStateException: cannot change build result while in COMPLETED
	at hudson.model.Run.setResult(Run.java:459)
	at hudson.plugins.doclinks.m2.DocLinksMavenReporter.end(DocLinksMavenReporter.java:97)
	at hudson.maven.AbstractMavenBuilder.end(AbstractMavenBuilder.java:104)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:859)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```
To circumvent this issue, I used a post-build step "Archive Artifact" instead. However, the integration with Doclinks would have been more appealing.

**Comment by ikedam** [comment]
Please file the issue to JIRA: https://issues.jenkins-ci.org/secure/Dashboard.jspa
